MT_MAP_WIDTH = 40
MT_MAP_HEIGHT = 24
MT_VIEWPORT_WIDTH = 15
MT_VIEWPORT_HEIGHT = 13
MT_NAMETABLE_WIDTH = 16
MT_NAMETABLE_HEIGHT = 15
MT_HSCROLL_MARGIN = 6
MT_VSCROLL_MARGIN = 5

PX_MT_WIDTH = 16
PX_MT_HEIGHT = 16

HEXFONT_BASE = $E0

;nametable info
TOP_HEIGHT = 18
BOTTOM_HEIGHT = 30
TOP_OFFSET = $180
TOP_ATTR_HEIGHT = 5
BOTTOM_ATTR_HEIGHT = 8
TOP_ATTR_OFFSET = $23C0+[3*8]
BOTTOM_ATTR_OFFSET = $2BC0

    SEG.U BEHAVIORS
    ORG $0000
TB_EMPTY:      ds 1 ;1
TB_SOLID:      ds 1 ;2
TB_PLATFORM:   ds 1 ;3
TB_EXIT:    ds 1 ;4
TB_DEADLY:     ds 1 ;5
TB_CRYSTAL:    ds 1 ;6
TB_LIGHTSON:   ds 1 ;7
TB_LIGHTSOFF:  ds 1 ;8
TB_WEAKBLOCK:  ds 1 ;9
TB_UNUSED:     ds 31 ;56
TB_MAPDOOR     ds 16
TB_OFF:        ds 4 ;60
TB_ON:         ds 4 ;64
